version: '3'

volumes:
  postgres_data: {}
  postgres_backup: {}


services:
  database:
    restart: always
    image: postgres:13-alpine
    container_name: script_db
    environment:
      - POSTGRES_PASSWORD=script_power
      - POSTGRES_USER=script_power
      - POSTGRES_DB=script_power
    ports:
      - "8092:5432" # to avoid local ports from clashing
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_backup:/backups
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U script_power"]
      interval: 5s
      timeout: 10s
      retries: 5

  # Using traefik as reverse proxy
  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.9
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock

  web:
    restart: always
    container_name: script_web
    user: "root:script"
    build:
        context: .
        dockerfile: Dockerfile
    volumes:
      - .:/app
    labels:
      - "traefik.http.routers.web.rule=Host(`script.docker.localhost`)"
    ports:
      - "8000:8000"
    depends_on:
      - database
    entrypoint: ["/bin/sh","-c"]
    command:
    - |
      pwd
      poetry run script/manage.py makemigrations
      poetry run script/manage.py migrate
      echo "from django.contrib.auth.models import User; User.objects.filter(email='admin@example.com').delete(); User.objects.create_superuser('devadmin', 'admin@example.com', 'nimda')" | poetry run script/manage.py shell
      echo Starting Django development server..
      poetry run script/manage.py runserver 0.0.0.0:8000
    environment:
      - DJANGO_SETTINGS_MODULE=script.settings.dev
      - DATABASE_URL=postgresql://script_power:script_power@database:5432/script_power
      - DB_NAME=script_power
      - DB_PORT=5432
      - DB_USER=script_power
      - DB_PASSWORD=script_power
      - DB_HOST=database
      - ENVIRONMENT=dev

networks:
  default:
      name: scripturesandpower
